---
plugin: amazon.aws.aws_ec2
regions:
  - us-east-2
# filters:
#   instance-state-name: running
#   tag:Name: dev-ec2-instance
hostnames:
  - ip-address
# compose:
#   ansible_host: public_ip_address
# keyed_groups:
#   - key: tags.Name
#     prefix: tag_Name
